### ISSUE TITLE
All searches now failing with KeyError: -1

### ISSUE THREAD

**Issue by peka7777777** [ChrisStevens/garc#11]
root:/app# garc search maga --number_gabs=1
Traceback (most recent call last):
  File "/usr/local/bin/garc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/garc/command.py", line 121, in main
    for thing in things:
  File "/usr/local/lib/python3.8/site-packages/garc/client.py", line 88, in search
    max_id = posts[-1]['id']
KeyError: -1

**Comment by peka7777777** [comment]
This seems to be a result of opening too many sessions with a single user account (I am running garc in ephemeral containers so each new instance creates a new session on the account), not sure if there is a programatic way to close down sessions once they are opened (Certainly possible from the UI) but looking more at it

**Comment by djkemmet** [comment]
Did you ever find a solution? i was using garc to research gba but it looks like I'm getting a     last_published_date = posts[-1]['created_at'] error now

**Comment by elleobrien** [comment]
I have this issue, too. I also don't have any other sessions running.
