### ISSUE TITLE
Getting a weird JSON error

### ISSUE THREAD

**Issue by julianividal** [ChrisStevens/garc#5]
Sorry to bother, but I'm attempting to use your tool to do some research but I can't get it to work. I have the newest version installed (with prosearch command) and yet I keep getting the following error:

> % garc prosearch wwg1wga 
> Traceback (most recent call last):
>   File "/usr/local/bin/garc", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/garc/command.py", line 129, in main
>     for thing in things:
>   File "/usr/local/lib/python3.9/site-packages/garc/client.py", line 115, in pro_search
>     posts = resp.json()
>   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I can't quite figure out how to fix this? Any help would be deeply appreciated.

**Comment by ChrisStevens** [comment]
@julianividal This is most likely an issue with Gab's current instability. 

They are having trouble with keeping the site up, which means that with how garc is written it will occasionally not get back a proper json response, which causes this error.

If you make sure Gab is up and try running your call again it should work. I need to add some better error catching and rest functionality so that it will wait and retry if there is a lack of response.

Could you please let me know if you are still getting this error after running it a few times? Certainly not the ideal solution, but I will try and add some better retry capabilities this weekend.
